In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('Heart.csv')

print("shape of dataset")        #finding the shape of data
df.shape

shape of dataset


(303, 15)

In [2]:
df                                # showing data

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [3]:
df.describe()             #describe data

Unnamed: 0         Age         Sex      RestBP        Chol         Fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean   152.000000   54.438944    0.679868  131.689769  246.693069    0.148515   
std     87.612784    9.038662    0.467299   17.599748   51.776918    0.356198   
min      1.000000   29.000000    0.000000   94.000000  126.000000    0.000000   
25%     76.500000   48.000000    0.000000  120.000000  211.000000    0.000000   
50%    152.000000   56.000000    1.000000  130.000000  241.000000    0.000000   
75%    227.500000   61.000000    1.000000  140.000000  275.000000    0.000000   
max    303.000000   77.000000    1.000000  200.000000  564.000000    1.000000   

          RestECG       MaxHR       ExAng     Oldpeak       Slope          Ca  
count  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000  
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.672241  
std      0.994971   22.875003    0.469794    1.161075    0.616226    0.937438  
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000  
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000  
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000  
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000  
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000

In [4]:
print("data type of each column==")        #all information show with datatypes
df.info()

data type of each column==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  303 non-null    int64  
 1   Age         303 non-null    int64  
 2   Sex         303 non-null    int64  
 3   ChestPain   303 non-null    object 
 4   RestBP      303 non-null    int64  
 5   Chol        303 non-null    int64  
 6   Fbs         303 non-null    int64  
 7   RestECG     303 non-null    int64  
 8   MaxHR       303 non-null    int64  
 9   ExAng       303 non-null    int64  
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64  
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    object 
 14  AHD         303 non-null    object 
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB


In [5]:
df.isnull()                    #showing null values ,null value indicated  as  true

Unnamed: 0    Age    Sex  ChestPain  RestBP   Chol    Fbs  RestECG  \
0         False  False  False      False   False  False  False    False   
1         False  False  False      False   False  False  False    False   
2         False  False  False      False   False  False  False    False   
3         False  False  False      False   False  False  False    False   
4         False  False  False      False   False  False  False    False   
..          ...    ...    ...        ...     ...    ...    ...      ...   
298       False  False  False      False   False  False  False    False   
299       False  False  False      False   False  False  False    False   
300       False  False  False      False   False  False  False    False   
301       False  False  False      False   False  False  False    False   
302       False  False  False      False   False  False  False    False   

     MaxHR  ExAng  Oldpeak  Slope     Ca   Thal    AHD  
0    False  False    False  False  False  False  False  
1    False  False    False  False  False  False  False  
2    False  False    False  False  False  False  False  
3    False  False    False  False  False  False  False  
4    False  False    False  False  False  False  False  
..     ...    ...      ...    ...    ...    ...    ...  
298  False  False    False  False  False  False  False  
299  False  False    False  False  False  False  False  
300  False  False    False  False  False  False  False  
301  False  False    False  False  False  False  False  
302  False  False    False  False   True  False  False  

[303 rows x 15 columns]

In [6]:
df.isnull().sum()        #where null value present that info is show

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [7]:
df[df['Ca'].isnull()]          #showing null value

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
166         167   52    1    nonanginal     138   223    0        0    169   
192         193   43    1  asymptomatic     132   247    1        2    143   
287         288   58    1    nontypical     125   220    0        0    144   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope  Ca        Thal  AHD  
166      0      0.0      1 NaN      normal   No  
192      1      0.1      2 NaN  reversable  Yes  
287      0      0.4      2 NaN  reversable   No  
302      0      0.0      1 NaN      normal   No

In [8]:
print("mean of Age column==")     #mean value show
df['Age'].mean(axis=0)

mean of Age column==


54.43894389438944

In [9]:
(df == 0).sum()         #numbers of zero present in dataset

Unnamed: 0      0
Age             0
Sex            97
ChestPain       0
RestBP          0
Chol            0
Fbs           258
RestECG       151
MaxHR           0
ExAng         204
Oldpeak        99
Slope           0
Ca            176
Thal            0
AHD             0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split              #spliting data using train_test_split

In [11]:
training_set,testing_set= train_test_split(df,test_size=0.25)

In [12]:
training_set

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
160         161   46    1    nontypical     101   197    1        0    156   
10           11   57    1  asymptomatic     140   192    0        0    148   
159         160   68    1    nonanginal     118   277    0        0    151   
279         280   58    0  asymptomatic     130   197    0        0    131   
130         131   54    1    nonanginal     120   258    0        2    147   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
251         252   58    1  asymptomatic     146   218    0        0    105   
162         163   54    0    nonanginal     110   214    0        0    158   
273         274   71    0  asymptomatic     112   149    0        0    125   
256         257   67    0  asymptomatic     106   223    0        0    142   
8             9   63    1  asymptomatic     130   254    0        2    147   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
160      0      0.0      1  0.0  reversable   No  
10       0      0.4      2  0.0       fixed   No  
159      0      1.0      1  1.0  reversable   No  
279      0      0.6      2  0.0      normal   No  
130      0      0.4      2  0.0  reversable   No  
..     ...      ...    ...  ...         ...  ...  
251      0      2.0      2  1.0  reversable  Yes  
162      0      1.6      2  0.0      normal   No  
273      0      1.6      2  0.0      normal   No  
256      0      0.3      1  2.0      normal   No  
8        0      1.4      2  1.0  reversable  Yes  

[227 rows x 15 columns]

In [13]:
testing_set

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
286         287   58    0  asymptomatic     170   225    1        2    146   
272         273   46    1  asymptomatic     140   311    0        0    120   
6             7   62    0  asymptomatic     140   268    0        2    160   
34           35   44    1    nonanginal     130   233    0        0    179   
60           61   51    0  asymptomatic     130   305    0        0    142   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
101         102   34    1       typical     118   182    0        2    174   
22           23   58    1    nontypical     120   284    0        2    160   
300         301   57    1  asymptomatic     130   131    0        0    115   
268         269   40    1  asymptomatic     152   223    0        0    181   
73           74   65    1  asymptomatic     110   248    0        2    158   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
286      1      2.8      2  2.0       fixed  Yes  
272      1      1.8      2  2.0  reversable  Yes  
6        0      3.6      3  2.0      normal  Yes  
34       1      0.4      1  0.0      normal   No  
60       1      1.2      2  0.0  reversable  Yes  
..     ...      ...    ...  ...         ...  ...  
101      0      0.0      1  0.0      normal   No  
22       0      1.8      2  0.0      normal  Yes  
300      1      1.2      2  1.0  reversable  Yes  
268      0      0.0      1  0.0  reversable  Yes  
73       0      0.6      1  2.0       fixed  Yes  

[76 rows x 15 columns]

In [14]:
testing_set.shape

(76, 15)

In [15]:
training_set.shape

(227, 15)

In [16]:
training = df[0:277]
testing=df[227:]

In [17]:
print(training.shape)
print(testing.shape)

(277, 15)
(76, 15)


In [18]:
y=df
X=df                            #spliting data using train_test_split    in another way

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=42)
X_train

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
287         288   58    1    nontypical     125   220    0        0    144   
282         283   55    0  asymptomatic     128   205    0        1    130   
197         198   45    0  asymptomatic     138   236    0        2    152   
158         159   60    1  asymptomatic     140   293    0        2    170   
164         165   48    1    nonanginal     124   255    1        0    175   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
188         189   54    1    nontypical     192   283    0        2    195   
71           72   67    1  asymptomatic     125   254    1        0    163   
106         107   59    1  asymptomatic     140   177    0        0    162   
270         271   61    1  asymptomatic     140   207    0        2    138   
102         103   57    0  asymptomatic     128   303    0        2    159   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
287      0      0.4      2  NaN  reversable   No  
282      1      2.0      2  1.0  reversable  Yes  
197      1      0.2      2  0.0      normal   No  
158      0      1.2      2  2.0  reversable  Yes  
164      0      0.0      1  2.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
188      0      0.0      1  1.0  reversable  Yes  
71       0      0.2      2  2.0  reversable  Yes  
106      1      0.0      1  1.0  reversable  Yes  
270      1      1.9      1  1.0  reversable  Yes  
102      0      0.0      1  1.0      normal   No  

[227 rows x 15 columns]

In [19]:
from sklearn.model_selection import KFold
kfs= KFold(n_splits=5,shuffle=False,random_state=None)             #spliting data using KFold

In [20]:
for train_data_index,test_data_index in kfs.split([1,2,3,4,5,6,7,8,9,0]):
    print(train_data_index,test_data_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [21]:
kfs= KFold(n_splits=5,shuffle=False,random_state=None)
for train_data_index,test_data_index in kfs.split(df):
     print(train_data_index,test_data_index)

[ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222
 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240
 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276
 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294
 295 296 297 298 299 300 301 302] [ 0  1  2  3  4  

In [22]:
from sklearn.model_selection import LeaveOneOut              #spliting data using LeaveOneOut

In [23]:
loo=LeaveOneOut()
for train_data_index,test_data_index in loo.split([1,2,3,4,5,6,7,8,9,0]):
    print(train_data_index,test_data_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [24]:
#loo= LeaveOneOut(n_splits=5,shuffle=False,random_state=None)
for train_data_index,test_data_index in loo.split(df):
     print(train_data_index,test_data_index)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [38]:
tp=45

In [39]:
tn=395

In [40]:
fn=5

In [41]:
fp=55

In [42]:
a=tp/(tp+fp)
print("precision",a)

precision 0.45


In [43]:
b=tp/(tp+fn)
print("recall",b)

recall 0.9


In [51]:
y_pred=np.zeros(500)
y_actual=np.zeros(500)

for i in range (0,50):
    y_actual[i]=1
    
    for i in range(5,105):    
        y_pred[i]=1


In [52]:
np.sum(y_actual)

50.0

In [53]:
np.sum(y_pred)

100.0

In [54]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("accuracy score:",accuracy_score(y_pred,y_actual))

accuracy score: 0.88


In [60]:
print("precision score:",precision_score(y_actual,y_pred))

precision score: 0.45


In [64]:
print(" recall score:",recall_score(y_actual,y_pred))

 recall score: 0.9


In [65]:
print(" f1 score:",f1_score(y_actual,y_pred))

 f1 score: 0.6


In [63]:
from sklearn.metrics import confusion_matrix         #TN FP
confusion_matrix(y_actual,y_pred)                    #FN TP

array([[395,  55],
       [  5,  45]], dtype=int64)

In [59]:
from sklearn.metrics import  classification_report
print(classification_report(y_actual,y_pred))

              precision    recall  f1-score   support

         0.0       0.99      0.88      0.93       450
         1.0       0.45      0.90      0.60        50

    accuracy                           0.88       500
   macro avg       0.72      0.89      0.76       500
weighted avg       0.93      0.88      0.90       500

